# Generated by Django 4.2.11 on 2024-09-06 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faoliyat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IchkiIdoraviyHujatlar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_uz', models.CharField(blank=True, max_length=255)),
                ('name_ru', models.CharField(blank=True, max_length=255)),
                ('name_en', models.CharField(blank=True, max_length=255)),
                ('fayl', models.FileField(upload_to='mormtiv_hujatlar')),
            ],
        ),
        migrations.CreateModel(
            name='NormativHujatlar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_uz', models.CharField(blank=True, max_length=255)),
                ('name_ru', models.CharField(blank=True, max_length=255)),
                ('name_en', models.CharField(blank=True, max_length=255)),
                ('fayl', models.FileField(upload_to='mormtiv_hujatlar')),
            ],
        ),
        migrations.CreateModel(
            name='XabarBerish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_uz', models.CharField(blank=True, max_length=255)),
                ('name_ru', models.CharField(blank=True, max_length=255)),
                ('name_en', models.CharField(blank=True, max_length=255)),
                ('fayl', models.FileField(upload_to='mormtiv_hujatlar')),
            ],
        ),
    ]
