# Generated by Django 4.2.11 on 2024-10-28 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faoliyat', '0002_ichkiidoraviyhujatlar_normativhujatlar_xabarberish'),
    ]

    operations = [
        migrations.CreateModel(
            name='XalqaroProfesorlarFikri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_uz', models.CharField(blank=True, max_length=200)),
                ('title_ru', models.CharField(blank=True, max_length=200)),
                ('title_en', models.CharField(blank=True, max_length=200)),
                ('fikr_uz', models.TextField(blank=True)),
                ('fikr_ru', models.TextField(blank=True)),
                ('fikr_en', models.TextField(blank=True)),
                ('fish_uz', models.CharField(blank=True, max_length=200)),
                ('fish_ru', models.CharField(blank=True, max_length=200)),
                ('fish_en', models.CharField(blank=True, max_length=200)),
                ('lavozim_uz', models.CharField(blank=True, max_length=200)),
                ('lavozim_ru', models.CharField(blank=True, max_length=200)),
                ('lavozim_en', models.CharField(blank=True, max_length=200)),
                ('rasm', models.ImageField(blank=True, upload_to='xalqaro_profesorlar/')),
                ('link', models.URLField(blank=True, max_length=500)),
            ],
        ),
    ]
