# Generated by Django 5.0.3 on 2024-06-06 06:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BakalavrFanDasturTuri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_uz', models.CharField(blank=True, max_length=255)),
                ('name_ru', models.CharField(blank=True, max_length=255)),
                ('name_en', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='BakalavrFanKatalogi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_uz', models.CharField(blank=True, max_length=255)),
                ('name_ru', models.CharField(blank=True, max_length=255)),
                ('name_en', models.CharField(blank=True, max_length=255)),
                ('fayl', models.FileField(upload_to='fan_katalogi/')),
                ('sana', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='BakalavrMalakaTalabi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_uz', models.CharField(blank=True, max_length=255)),
                ('name_ru', models.CharField(blank=True, max_length=255)),
                ('name_en', models.CharField(blank=True, max_length=255)),
                ('fayl', models.FileField(upload_to='malaka_talab/')),
                ('sana', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='BakalavrOquvRejaTuri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_uz', models.CharField(blank=True, max_length=255)),
                ('name_ru', models.CharField(blank=True, max_length=255)),
                ('name_en', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TalabaBakalavr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_uz', models.CharField(blank=True, max_length=255)),
                ('title_ru', models.CharField(blank=True, max_length=255)),
                ('title_en', models.CharField(blank=True, max_length=255)),
                ('body_uz', models.TextField(blank=True)),
                ('body_ru', models.TextField(blank=True)),
                ('body_en', models.TextField(blank=True)),
                ('rasm', models.ImageField(blank=True, upload_to='bakalavr/')),
            ],
        ),
        migrations.CreateModel(
            name='TalabaMagistr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_uz', models.CharField(blank=True, max_length=255)),
                ('title_ru', models.CharField(blank=True, max_length=255)),
                ('title_en', models.CharField(blank=True, max_length=255)),
                ('body_uz', models.TextField(blank=True)),
                ('body_ru', models.TextField(blank=True)),
                ('body_en', models.TextField(blank=True)),
                ('rasm', models.ImageField(blank=True, upload_to='magistr/')),
            ],
        ),
        migrations.CreateModel(
            name='BakalavrFanDastur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_uz', models.CharField(blank=True, max_length=255)),
                ('name_ru', models.CharField(blank=True, max_length=255)),
                ('name_en', models.CharField(blank=True, max_length=255)),
                ('fayl', models.FileField(upload_to='fan_dastur/')),
                ('sana', models.CharField(blank=True, max_length=255)),
                ('oquv_reja_turi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='talaba.bakalavrfandasturturi')),
            ],
        ),
        migrations.CreateModel(
            name='BakalavrOquvReja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_uz', models.CharField(blank=True, max_length=255)),
                ('name_ru', models.CharField(blank=True, max_length=255)),
                ('name_en', models.CharField(blank=True, max_length=255)),
                ('fayl', models.FileField(upload_to='oquv_reja/')),
                ('sana', models.CharField(blank=True, max_length=255)),
                ('oquv_reja_turi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='talaba.bakalavroquvrejaturi')),
            ],
        ),
    ]
