# Generated by Django 5.0.3 on 2024-06-06 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('talaba', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bakalavrfandastur',
            old_name='oquv_reja_turi',
            new_name='fan_dastur_turi_id',
        ),
        migrations.RenameField(
            model_name='bakalavroquvreja',
            old_name='oquv_reja_turi',
            new_name='oquv_reja_turi_id',
        ),
    ]
