# Generated by Django 4.2.11 on 2024-06-28 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talaba', '0002_rename_oquv_reja_turi_bakalavrfandastur_fan_dastur_turi_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TTJAriza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_1_title_uz', models.CharField(blank=True, max_length=255)),
                ('link_1_title_ru', models.CharField(blank=True, max_length=255)),
                ('link_1_title_en', models.CharField(blank=True, max_length=255)),
                ('link_1', models.CharField(blank=True, max_length=255)),
                ('link_2_title_uz', models.CharField(blank=True, max_length=255)),
                ('link_2_title_ru', models.CharField(blank=True, max_length=255)),
                ('link_2_title_en', models.CharField(blank=True, max_length=255)),
                ('link_2', models.CharField(blank=True, max_length=255)),
                ('link_3_title_uz', models.CharField(blank=True, max_length=255)),
                ('link_3_title_ru', models.CharField(blank=True, max_length=255)),
                ('link_3_title_en', models.CharField(blank=True, max_length=255)),
                ('link_3', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TTJCampus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_uz', models.CharField(blank=True, max_length=255)),
                ('title_ru', models.CharField(blank=True, max_length=255)),
                ('title_en', models.CharField(blank=True, max_length=255)),
                ('body_uz', models.CharField(blank=True, max_length=255)),
                ('body_ru', models.CharField(blank=True, max_length=255)),
                ('body_en', models.CharField(blank=True, max_length=255)),
                ('rasm', models.ImageField(blank=True, upload_to='ttjcampus')),
            ],
        ),
        migrations.CreateModel(
            name='TTJRahbar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_uz', models.CharField(blank=True, max_length=255)),
                ('title_ru', models.CharField(blank=True, max_length=255)),
                ('title_en', models.CharField(blank=True, max_length=255)),
                ('body_uz', models.CharField(blank=True, max_length=255)),
                ('body_ru', models.CharField(blank=True, max_length=255)),
                ('body_en', models.CharField(blank=True, max_length=255)),
                ('rasm', models.ImageField(blank=True, upload_to='ttjrahbar')),
                ('rahbar_fish', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TTJStatistika',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('talabalar', models.CharField(blank=True, max_length=255)),
                ('xonalar', models.CharField(blank=True, max_length=255)),
                ('binolar', models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
