# Generated by Django 4.2.11 on 2024-09-11 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('talaba', '0003_ttjariza_ttjcampus_ttjrahbar_ttjstatistika'),
    ]

    operations = [
        migrations.CreateModel(
            name='MagistrFanDasturTuri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_uz', models.CharField(blank=True, max_length=255)),
                ('name_ru', models.CharField(blank=True, max_length=255)),
                ('name_en', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='MagistrFanKatalogi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_uz', models.CharField(blank=True, max_length=255)),
                ('name_ru', models.CharField(blank=True, max_length=255)),
                ('name_en', models.CharField(blank=True, max_length=255)),
                ('fayl', models.FileField(upload_to='fan_katalogi/')),
                ('sana', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='MagistrMalakaTalabi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_uz', models.CharField(blank=True, max_length=255)),
                ('name_ru', models.CharField(blank=True, max_length=255)),
                ('name_en', models.CharField(blank=True, max_length=255)),
                ('fayl', models.FileField(upload_to='malaka_talab/')),
                ('sana', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='MagistrOquvRejaTuri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_uz', models.CharField(blank=True, max_length=255)),
                ('name_ru', models.CharField(blank=True, max_length=255)),
                ('name_en', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='MagistrOquvReja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_uz', models.CharField(blank=True, max_length=255)),
                ('name_ru', models.CharField(blank=True, max_length=255)),
                ('name_en', models.CharField(blank=True, max_length=255)),
                ('fayl', models.FileField(upload_to='oquv_reja/')),
                ('sana', models.CharField(blank=True, max_length=255)),
                ('oquv_reja_turi_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='talaba.magistroquvrejaturi')),
            ],
        ),
        migrations.CreateModel(
            name='MagistrFanDastur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_uz', models.CharField(blank=True, max_length=255)),
                ('name_ru', models.CharField(blank=True, max_length=255)),
                ('name_en', models.CharField(blank=True, max_length=255)),
                ('fayl', models.FileField(upload_to='fan_dastur/')),
                ('sana', models.CharField(blank=True, max_length=255)),
                ('fan_dastur_turi_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='talaba.magistrfandasturturi')),
            ],
        ),
    ]
