# Generated by Django 4.2.11 on 2024-09-15 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('talaba', '0004_magistrfandasturturi_magistrfankatalogi_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BakalavrFanDasturKurs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_uz', models.CharField(blank=True, max_length=255)),
                ('name_ru', models.CharField(blank=True, max_length=255)),
                ('name_en', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='MagistrFanDasturKurs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_uz', models.CharField(blank=True, max_length=255)),
                ('name_ru', models.CharField(blank=True, max_length=255)),
                ('name_en', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='MagistrFanDasturYonalish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_uz', models.CharField(blank=True, max_length=255)),
                ('name_ru', models.CharField(blank=True, max_length=255)),
                ('name_en', models.CharField(blank=True, max_length=255)),
                ('fan_dastur_kurs_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='talaba.magistrfandasturkurs')),
            ],
        ),
        migrations.CreateModel(
            name='BakalavrFanDasturYonalish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_uz', models.CharField(blank=True, max_length=255)),
                ('name_ru', models.CharField(blank=True, max_length=255)),
                ('name_en', models.CharField(blank=True, max_length=255)),
                ('fan_dastur_kurs_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='talaba.bakalavrfandasturkurs')),
            ],
        ),
        migrations.AddField(
            model_name='bakalavrfandasturturi',
            name='fan_dastur_yonalish_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='talaba.bakalavrfandasturyonalish'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='magistrfandasturturi',
            name='fan_dastur_yonalish_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='talaba.magistrfandasturyonalish'),
            preserve_default=False,
        ),
    ]
