# Generated by Django 4.2.11 on 2024-09-18 05:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('talaba', '0005_bakalavrfandasturkurs_magistrfandasturkurs_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bakalavrfandasturyonalish',
            name='fan_dastur_kurs_id',
        ),
        migrations.CreateModel(
            name='BakalavrFanDasturTalimTuri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_uz', models.CharField(blank=True, max_length=255)),
                ('name_ru', models.CharField(blank=True, max_length=255)),
                ('name_en', models.CharField(blank=True, max_length=255)),
                ('fan_dastur_kurs_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='talaba.bakalavrfandasturkurs')),
            ],
        ),
        migrations.AddField(
            model_name='bakalavrfandasturyonalish',
            name='fan_dastur_talim_turi_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='talaba.bakalavrfandasturtalimturi'),
            preserve_default=False,
        ),
    ]
