# Generated by Django 5.0.3 on 2024-03-21 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Yangilik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rasm_0', models.ImageField(upload_to='yangilik/')),
                ('rasm_1', models.ImageField(upload_to='yangilik/')),
                ('rasm_2', models.ImageField(upload_to='yangilik/')),
                ('rasm_3', models.ImageField(upload_to='yangilik/')),
                ('rasm_4', models.ImageField(upload_to='yangilik/')),
                ('title', models.CharField(max_length=500)),
                ('subtitle', models.CharField(blank=True, max_length=500)),
                ('body_0', models.TextField()),
                ('body_1', models.TextField(blank=True)),
                ('body_2', models.TextField(blank=True)),
                ('body_3', models.TextField(blank=True)),
                ('body_4', models.TextField(blank=True)),
                ('body_5', models.TextField(blank=True)),
                ('body_6', models.TextField(blank=True)),
                ('body_7', models.TextField(blank=True)),
                ('body_8', models.TextField(blank=True)),
                ('body_9', models.TextField(blank=True)),
            ],
        ),
    ]
