# Generated by Django 5.0.3 on 2024-03-22 19:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yangilik', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Til',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('uz', 'uz'), ('ru', 'ru'), ('en', 'en')], max_length=5)),
            ],
        ),
        migrations.AddField(
            model_name='yangilik',
            name='til',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='yangilik.til'),
            preserve_default=False,
        ),
    ]
