# Generated by Django 5.0.3 on 2024-03-22 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yangilik', '0002_til_yangilik_til'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yangilik',
            name='rasm_1',
            field=models.ImageField(blank=True, upload_to='yangilik/'),
        ),
        migrations.AlterField(
            model_name='yangilik',
            name='rasm_2',
            field=models.ImageField(blank=True, upload_to='yangilik/'),
        ),
        migrations.AlterField(
            model_name='yangilik',
            name='rasm_3',
            field=models.ImageField(blank=True, upload_to='yangilik/'),
        ),
        migrations.AlterField(
            model_name='yangilik',
            name='rasm_4',
            field=models.ImageField(blank=True, upload_to='yangilik/'),
        ),
    ]
