# Generated by Django 5.0.3 on 2024-03-23 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yangilik', '0003_alter_yangilik_rasm_1_alter_yangilik_rasm_2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='yangilik',
            name='til',
        ),
        migrations.AddField(
            model_name='yangilik',
            name='til',
            field=models.ManyToManyField(to='yangilik.til'),
        ),
    ]
