# Generated by Django 5.0.3 on 2024-03-23 11:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yangilik', '0004_remove_yangilik_til_yangilik_til'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='yangilik',
            name='til',
        ),
        migrations.CreateModel(
            name='Sinov',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yangilik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yangilik.til')),
            ],
        ),
        migrations.AddField(
            model_name='yangilik',
            name='til',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='yangilik.til'),
            preserve_default=False,
        ),
    ]
