# Generated by Django 5.0.3 on 2024-03-23 12:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yangilik', '0005_remove_yangilik_til_sinov_yangilik_til'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sinov',
            name='yangilik',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yangilik.yangilik'),
        ),
    ]
