# Generated by Django 5.0.3 on 2024-03-23 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yangilik', '0006_alter_sinov_yangilik'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sinov',
            name='yangilik',
        ),
        migrations.AddField(
            model_name='sinov',
            name='yangilik',
            field=models.ManyToManyField(to='yangilik.yangilik'),
        ),
    ]
