# Generated by Django 5.0.3 on 2024-03-23 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yangilik', '0007_remove_sinov_yangilik_sinov_yangilik'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='yangilik',
            options={'ordering': ['title']},
        ),
    ]
