# Generated by Django 5.0.3 on 2024-03-23 15:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yangilik', '0008_alter_yangilik_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='sinov',
            name='sinov',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='models', related_query_name='model', to='yangilik.yangilik'),
        ),
    ]
