# Generated by Django 5.0.3 on 2024-03-23 15:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yangilik', '0009_sinov_sinov'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sinov',
            name='sinov',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='models', related_query_name='model', to='yangilik.yangilik'),
        ),
    ]
