# Generated by Django 5.0.3 on 2024-03-23 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yangilik', '0011_alter_yangilik_options_remove_sinov_sinov_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sinov',
            name='yangilik',
            field=models.ManyToManyField(to='yangilik.yangilik'),
        ),
        migrations.RemoveField(
            model_name='yangilik',
            name='til',
        ),
        migrations.AddField(
            model_name='yangilik',
            name='til',
            field=models.ManyToManyField(to='yangilik.til'),
        ),
    ]
