# Generated by Django 5.0.3 on 2024-03-24 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yangilik', '0012_alter_sinov_yangilik_remove_yangilik_til_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Malumot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('son', models.IntegerField()),
                ('data', models.ManyToManyField(to='yangilik.sinov')),
            ],
        ),
    ]
