# Generated by Django 5.0.3 on 2024-03-25 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yangilik', '0013_malumot'),
    ]

    operations = [
        migrations.AddField(
            model_name='sinov',
            name='til',
            field=models.ManyToManyField(to='yangilik.til'),
        ),
    ]
