# Generated by Django 5.0.3 on 2024-03-25 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yangilik', '0014_sinov_til'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='yangilik',
            name='til',
        ),
    ]
