# Generated by Django 5.0.3 on 2024-03-25 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yangilik', '0015_remove_yangilik_til'),
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('uz', 'uz'), ('ru', 'ru'), ('en', 'en')], max_length=5)),
            ],
        ),
        migrations.AddField(
            model_name='til',
            name='content',
            field=models.ManyToManyField(to='yangilik.content'),
        ),
    ]
