# Generated by Django 5.0.3 on 2024-03-25 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yangilik', '0016_content_til_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='yangilik',
            name='body_0',
        ),
        migrations.RemoveField(
            model_name='yangilik',
            name='body_1',
        ),
        migrations.RemoveField(
            model_name='yangilik',
            name='body_2',
        ),
        migrations.RemoveField(
            model_name='yangilik',
            name='body_3',
        ),
        migrations.RemoveField(
            model_name='yangilik',
            name='body_4',
        ),
        migrations.RemoveField(
            model_name='yangilik',
            name='body_5',
        ),
        migrations.RemoveField(
            model_name='yangilik',
            name='body_6',
        ),
        migrations.RemoveField(
            model_name='yangilik',
            name='body_7',
        ),
        migrations.RemoveField(
            model_name='yangilik',
            name='body_8',
        ),
        migrations.RemoveField(
            model_name='yangilik',
            name='body_9',
        ),
        migrations.RemoveField(
            model_name='yangilik',
            name='subtitle',
        ),
        migrations.RemoveField(
            model_name='yangilik',
            name='title',
        ),
        migrations.AddField(
            model_name='content',
            name='body_0',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='content',
            name='body_1',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='content',
            name='body_2',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='content',
            name='body_3',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='content',
            name='body_4',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='content',
            name='body_5',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='content',
            name='body_6',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='content',
            name='body_7',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='content',
            name='body_8',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='content',
            name='body_9',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='content',
            name='subtitle',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='content',
            name='title',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='content',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
