# Generated by Django 5.0.3 on 2024-03-25 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yangilik', '0018_yangilik_til'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='til',
            name='content',
        ),
        migrations.RemoveField(
            model_name='yangilik',
            name='til',
        ),
        migrations.AddField(
            model_name='content',
            name='content',
            field=models.ManyToManyField(to='yangilik.til'),
        ),
        migrations.AddField(
            model_name='yangilik',
            name='content',
            field=models.ManyToManyField(to='yangilik.content'),
        ),
    ]
