# Generated by Django 5.0.3 on 2024-03-25 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yangilik', '0019_remove_til_content_remove_yangilik_til_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='content',
        ),
        migrations.AddField(
            model_name='content',
            name='json',
            field=models.JSONField(default=1),
            preserve_default=False,
        ),
    ]
