# Generated by Django 5.0.3 on 2024-03-25 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yangilik', '0021_remove_yangilik_content_remove_malumot_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='yangilik',
            name='sana',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
