# Generated by Django 5.0.3 on 2024-03-25 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yangilik', '0022_yangilik_sana'),
    ]

    operations = [
        migrations.CreateModel(
            name='Elon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rasm', models.ImageField(upload_to='elon/')),
                ('title', models.CharField(max_length=1500)),
                ('detail', models.TextField()),
                ('boshlanish_vaqti', models.CharField(max_length=500)),
                ('tugash_vaqti', models.CharField(max_length=500)),
                ('field', models.TextField()),
                ('adress', models.CharField(max_length=500)),
                ('sana', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
