# Generated by Django 5.0.3 on 2024-05-20 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CallMarkaz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_uz', models.CharField(blank=True, max_length=255)),
                ('title_ru', models.CharField(blank=True, max_length=255)),
                ('title_en', models.CharField(blank=True, max_length=255)),
                ('body_uz', models.TextField(blank=True)),
                ('body_ru', models.TextField(blank=True)),
                ('body_en', models.TextField(blank=True)),
                ('nomer', models.TextField(blank=True)),
            ],
        ),
    ]
