# Generated by Django 5.0.3 on 2024-05-20 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('abiturient', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='callmarkaz',
            old_name='nomer',
            new_name='tel_nomer',
        ),
    ]
