# Generated by Django 5.0.3 on 2024-05-31 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abiturient', '0002_rename_nomer_callmarkaz_tel_nomer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bakalavr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_uz', models.CharField(blank=True, max_length=255)),
                ('title_ru', models.CharField(blank=True, max_length=255)),
                ('title_en', models.CharField(blank=True, max_length=255)),
                ('body_uz', models.TextField(blank=True)),
                ('body_ru', models.TextField(blank=True)),
                ('body_en', models.TextField(blank=True)),
                ('rasm', models.ImageField(blank=True, upload_to='bakalavr/')),
            ],
        ),
        migrations.CreateModel(
            name='Magistr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_uz', models.CharField(blank=True, max_length=255)),
                ('title_ru', models.CharField(blank=True, max_length=255)),
                ('title_en', models.CharField(blank=True, max_length=255)),
                ('body_uz', models.TextField(blank=True)),
                ('body_ru', models.TextField(blank=True)),
                ('body_en', models.TextField(blank=True)),
                ('rasm', models.ImageField(blank=True, upload_to='magistr/')),
            ],
        ),
        migrations.CreateModel(
            name='QabulHujjati',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('fayl', models.FileField(blank=True, upload_to='qabulhujati/')),
            ],
        ),
        migrations.RemoveField(
            model_name='callmarkaz',
            name='tel_nomer',
        ),
        migrations.AddField(
            model_name='callmarkaz',
            name='tel_nomer_1',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='callmarkaz',
            name='tel_nomer_2',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='callmarkaz',
            name='tel_nomer_3',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='callmarkaz',
            name='tel_nomer_4',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='callmarkaz',
            name='tel_nomer_5',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
