# Generated by Django 5.0.3 on 2024-06-01 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abiturient', '0004_alter_bakalavr_id_alter_callmarkaz_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bakalavr',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='callmarkaz',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='magistr',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='qabulhujjati',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
