# Generated by Django 5.0.3 on 2024-06-06 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('abiturient', '0005_alter_bakalavr_id_alter_callmarkaz_id_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bakalavr',
            new_name='AbiturientBakalavr',
        ),
        migrations.RenameModel(
            old_name='Magistr',
            new_name='AbiturientMagistr',
        ),
    ]
