# Generated by Django 5.0.3 on 2024-04-27 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InstitutHaqida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bizning_maqsadimiz_title_uz', models.CharField(blank=True, max_length=255)),
                ('bizning_maqsadimiz_title_ru', models.CharField(blank=True, max_length=255)),
                ('bizning_maqsadimiz_title_en', models.CharField(blank=True, max_length=255)),
                ('bizning_maqsadimiz_text_uz', models.TextField(blank=True)),
                ('bizning_maqsadimiz_text_ru', models.TextField(blank=True)),
                ('bizning_maqsadimiz_text_en', models.TextField(blank=True)),
                ('biz_haqimizda_title_uz', models.CharField(blank=True, max_length=255)),
                ('biz_haqimizda_title_ru', models.CharField(blank=True, max_length=255)),
                ('biz_haqimizda_title_en', models.CharField(blank=True, max_length=255)),
                ('biz_haqimizda_text_uz', models.TextField(blank=True)),
                ('biz_haqimizda_text_ru', models.TextField(blank=True)),
                ('biz_haqimizda_text_en', models.TextField(blank=True)),
                ('institut_rasm', models.FileField(blank=True, upload_to='institut_rasm/')),
                ('qoshimcha_title_uz', models.CharField(blank=True, max_length=255)),
                ('qoshimcha_title_ru', models.CharField(blank=True, max_length=255)),
                ('qoshimcha_title_en', models.CharField(blank=True, max_length=255)),
                ('biz_kimmiz_title_uz', models.CharField(blank=True, max_length=255)),
                ('biz_kimmiz_title_ru', models.CharField(blank=True, max_length=255)),
                ('biz_kimmiz_title_en', models.CharField(blank=True, max_length=255)),
                ('biz_kimmiz_text_uz', models.TextField(blank=True)),
                ('biz_kimmiz_text_ru', models.TextField(blank=True)),
                ('biz_kimmiz_text_en', models.TextField(blank=True)),
                ('biz_kimmiz', models.FileField(blank=True, upload_to='biz_kimmiz/')),
                ('qoshma_hamkorlar_title_uz', models.CharField(blank=True, max_length=255)),
                ('qoshma_hamkorlar_title_ru', models.CharField(blank=True, max_length=255)),
                ('qoshma_hamkorlar_title_en', models.CharField(blank=True, max_length=255)),
                ('qoshma_hamkorlar_text_uz', models.TextField(blank=True)),
                ('qoshma_hamkorlar_text_ru', models.TextField(blank=True)),
                ('qoshma_hamkorlar_text_en', models.TextField(blank=True)),
                ('qoshma_hamkorlar', models.FileField(blank=True, upload_to='qoshma_hamkorlar/')),
                ('rivojlanayotgan_talabalar_hayoti_title_uz', models.CharField(blank=True, max_length=255)),
                ('rivojlanayotgan_talabalar_hayoti_title_ru', models.CharField(blank=True, max_length=255)),
                ('rivojlanayotgan_talabalar_hayoti_title_en', models.CharField(blank=True, max_length=255)),
                ('rivojlanayotgan_talabalar_hayoti_text_uz', models.TextField(blank=True)),
                ('rivojlanayotgan_talabalar_hayoti_text_ru', models.TextField(blank=True)),
                ('rivojlanayotgan_talabalar_hayoti_text_en', models.TextField(blank=True)),
                ('rivojlanayotgan_talabalar_hayoti', models.FileField(blank=True, upload_to='rivojlanayotgan_talabalar_hayoti/')),
                ('kirish_title_uz', models.CharField(blank=True, max_length=255)),
                ('kirish_title_ru', models.CharField(blank=True, max_length=255)),
                ('kirish_title_en', models.CharField(blank=True, max_length=255)),
                ('barcha_shakillar_title_uz', models.CharField(blank=True, max_length=255)),
                ('barcha_shakillar_title_ru', models.CharField(blank=True, max_length=255)),
                ('barcha_shakillar_title_en', models.CharField(blank=True, max_length=255)),
                ('barcha_shakillar_text_uz', models.TextField(blank=True)),
                ('barcha_shakillar_text_ru', models.TextField(blank=True)),
                ('barcha_shakillar_text_en', models.TextField(blank=True)),
                ('barcha_shakillar', models.FileField(blank=True, upload_to='barcha_shakillar/')),
                ('moliyaviy_yordam_title_uz', models.CharField(blank=True, max_length=255)),
                ('moliyaviy_yordam_title_ru', models.CharField(blank=True, max_length=255)),
                ('moliyaviy_yordam_title_en', models.CharField(blank=True, max_length=255)),
                ('moliyaviy_yordam_text_uz', models.TextField(blank=True)),
                ('moliyaviy_yordam_text_ru', models.TextField(blank=True)),
                ('moliyaviy_yordam_text_en', models.TextField(blank=True)),
                ('moliyaviy_yordam', models.FileField(blank=True, upload_to='moliyaviy_yordam/')),
                ('sport_bilan_birga_title_uz', models.CharField(blank=True, max_length=255)),
                ('sport_bilan_birga_title_ru', models.CharField(blank=True, max_length=255)),
                ('sport_bilan_birga_title_en', models.CharField(blank=True, max_length=255)),
                ('sport_bilan_birga_text_uz', models.TextField(blank=True)),
                ('sport_bilan_birga_text_ru', models.TextField(blank=True)),
                ('sport_bilan_birga_text_en', models.TextField(blank=True)),
                ('sport_bilan_birga', models.FileField(blank=True, upload_to='sport_bilan_birga/')),
            ],
        ),
    ]
