# Generated by Django 5.0.3 on 2024-05-30 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institut', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankRekviziti',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_uz', models.CharField(blank=True, max_length=255)),
                ('name_ru', models.CharField(blank=True, max_length=255)),
                ('name_en', models.CharField(blank=True, max_length=255)),
                ('qiymat_uz', models.CharField(blank=True, max_length=255)),
                ('qiymat_ru', models.CharField(blank=True, max_length=255)),
                ('qiymat_en', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='InstitutMalumotlari',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_uz', models.CharField(blank=True, max_length=255)),
                ('title_ru', models.CharField(blank=True, max_length=255)),
                ('title_en', models.CharField(blank=True, max_length=255)),
                ('body_uz', models.TextField(blank=True)),
                ('body_ru', models.TextField(blank=True)),
                ('body_en', models.TextField(blank=True)),
                ('rasm', models.ImageField(blank=True, upload_to='tadbir/rasm/')),
                ('fayl', models.FileField(blank=True, upload_to='tadbir/fayl/')),
            ],
        ),
        migrations.CreateModel(
            name='InstitutRekviziti',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_uz', models.CharField(blank=True, max_length=255)),
                ('name_ru', models.CharField(blank=True, max_length=255)),
                ('name_en', models.CharField(blank=True, max_length=255)),
                ('qiymat_uz', models.CharField(blank=True, max_length=255)),
                ('qiymat_ru', models.CharField(blank=True, max_length=255)),
                ('qiymat_en', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Kengash',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fish', models.CharField(blank=True, max_length=255)),
                ('telefon', models.CharField(blank=True, max_length=255)),
                ('email', models.EmailField(blank=True, max_length=255)),
                ('kengash_vazifasi', models.TextField(blank=True)),
                ('kengash_haqida', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Qabulxona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fish', models.CharField(blank=True, max_length=255)),
                ('telefon_nomer', models.CharField(blank=True, max_length=255)),
                ('email', models.EmailField(blank=True, max_length=255)),
                ('mavzu', models.TextField(blank=True)),
                ('xabar', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tuzilma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_uz', models.CharField(blank=True, max_length=255)),
                ('name_ru', models.CharField(blank=True, max_length=255)),
                ('name_en', models.CharField(blank=True, max_length=255)),
                ('rasm_1', models.ImageField(blank=True, upload_to='tuzilma/')),
                ('rasm_2', models.ImageField(blank=True, upload_to='tuzilma/')),
                ('rasm_3', models.ImageField(blank=True, upload_to='tuzilma/')),
                ('rasm_4', models.ImageField(blank=True, upload_to='tuzilma/')),
                ('rasm_5', models.ImageField(blank=True, upload_to='tuzilma/')),
                ('pdf_fayl', models.FileField(blank=True, upload_to='tuzilma/')),
            ],
        ),
        migrations.RenameField(
            model_name='instituthaqida',
            old_name='barcha_shakillar_text_en',
            new_name='body_en',
        ),
        migrations.RenameField(
            model_name='instituthaqida',
            old_name='barcha_shakillar_text_ru',
            new_name='body_ru',
        ),
        migrations.RenameField(
            model_name='instituthaqida',
            old_name='barcha_shakillar_text_uz',
            new_name='body_uz',
        ),
        migrations.RenameField(
            model_name='instituthaqida',
            old_name='barcha_shakillar_title_en',
            new_name='title_en',
        ),
        migrations.RenameField(
            model_name='instituthaqida',
            old_name='barcha_shakillar_title_ru',
            new_name='title_ru',
        ),
        migrations.RenameField(
            model_name='instituthaqida',
            old_name='barcha_shakillar_title_uz',
            new_name='title_uz',
        ),
        migrations.RemoveField(
            model_name='instituthaqida',
            name='barcha_shakillar',
        ),
        migrations.RemoveField(
            model_name='instituthaqida',
            name='biz_haqimizda_text_en',
        ),
        migrations.RemoveField(
            model_name='instituthaqida',
            name='biz_haqimizda_text_ru',
        ),
        migrations.RemoveField(
            model_name='instituthaqida',
            name='biz_haqimizda_text_uz',
        ),
        migrations.RemoveField(
            model_name='instituthaqida',
            name='biz_haqimizda_title_en',
        ),
        migrations.RemoveField(
            model_name='instituthaqida',
            name='biz_haqimizda_title_ru',
        ),
        migrations.RemoveField(
            model_name='instituthaqida',
            name='biz_haqimizda_title_uz',
        ),
        migrations.RemoveField(
            model_name='instituthaqida',
            name='biz_kimmiz',
        ),
        migrations.RemoveField(
            model_name='instituthaqida',
            name='biz_kimmiz_text_en',
        ),
        migrations.RemoveField(
            model_name='instituthaqida',
            name='biz_kimmiz_text_ru',
        ),
        migrations.RemoveField(
            model_name='instituthaqida',
            name='biz_kimmiz_text_uz',
        ),
        migrations.RemoveField(
            model_name='instituthaqida',
            name='biz_kimmiz_title_en',
        ),
        migrations.RemoveField(
            model_name='instituthaqida',
            name='biz_kimmiz_title_ru',
        ),
        migrations.RemoveField(
            model_name='instituthaqida',
            name='biz_kimmiz_title_uz',
        ),
        migrations.RemoveField(
            model_name='instituthaqida',
            name='bizning_maqsadimiz_text_en',
        ),
        migrations.RemoveField(
            model_name='instituthaqida',
            name='bizning_maqsadimiz_text_ru',
        ),
        migrations.RemoveField(
            model_name='instituthaqida',
            name='bizning_maqsadimiz_text_uz',
        ),
        migrations.RemoveField(
            model_name='instituthaqida',
            name='bizning_maqsadimiz_title_en',
        ),
        migrations.RemoveField(
            model_name='instituthaqida',
            name='bizning_maqsadimiz_title_ru',
        ),
        migrations.RemoveField(
            model_name='instituthaqida',
            name='bizning_maqsadimiz_title_uz',
        ),
        migrations.RemoveField(
            model_name='instituthaqida',
            name='institut_rasm',
        ),
        migrations.RemoveField(
            model_name='instituthaqida',
            name='kirish_title_en',
        ),
        migrations.RemoveField(
            model_name='instituthaqida',
            name='kirish_title_ru',
        ),
        migrations.RemoveField(
            model_name='instituthaqida',
            name='kirish_title_uz',
        ),
        migrations.RemoveField(
            model_name='instituthaqida',
            name='moliyaviy_yordam',
        ),
        migrations.RemoveField(
            model_name='instituthaqida',
            name='moliyaviy_yordam_text_en',
        ),
        migrations.RemoveField(
            model_name='instituthaqida',
            name='moliyaviy_yordam_text_ru',
        ),
        migrations.RemoveField(
            model_name='instituthaqida',
            name='moliyaviy_yordam_text_uz',
        ),
        migrations.RemoveField(
            model_name='instituthaqida',
            name='moliyaviy_yordam_title_en',
        ),
        migrations.RemoveField(
            model_name='instituthaqida',
            name='moliyaviy_yordam_title_ru',
        ),
        migrations.RemoveField(
            model_name='instituthaqida',
            name='moliyaviy_yordam_title_uz',
        ),
        migrations.RemoveField(
            model_name='instituthaqida',
            name='qoshimcha_title_en',
        ),
        migrations.RemoveField(
            model_name='instituthaqida',
            name='qoshimcha_title_ru',
        ),
        migrations.RemoveField(
            model_name='instituthaqida',
            name='qoshimcha_title_uz',
        ),
        migrations.RemoveField(
            model_name='instituthaqida',
            name='qoshma_hamkorlar',
        ),
        migrations.RemoveField(
            model_name='instituthaqida',
            name='qoshma_hamkorlar_text_en',
        ),
        migrations.RemoveField(
            model_name='instituthaqida',
            name='qoshma_hamkorlar_text_ru',
        ),
        migrations.RemoveField(
            model_name='instituthaqida',
            name='qoshma_hamkorlar_text_uz',
        ),
        migrations.RemoveField(
            model_name='instituthaqida',
            name='qoshma_hamkorlar_title_en',
        ),
        migrations.RemoveField(
            model_name='instituthaqida',
            name='qoshma_hamkorlar_title_ru',
        ),
        migrations.RemoveField(
            model_name='instituthaqida',
            name='qoshma_hamkorlar_title_uz',
        ),
        migrations.RemoveField(
            model_name='instituthaqida',
            name='rivojlanayotgan_talabalar_hayoti',
        ),
        migrations.RemoveField(
            model_name='instituthaqida',
            name='rivojlanayotgan_talabalar_hayoti_text_en',
        ),
        migrations.RemoveField(
            model_name='instituthaqida',
            name='rivojlanayotgan_talabalar_hayoti_text_ru',
        ),
        migrations.RemoveField(
            model_name='instituthaqida',
            name='rivojlanayotgan_talabalar_hayoti_text_uz',
        ),
        migrations.RemoveField(
            model_name='instituthaqida',
            name='rivojlanayotgan_talabalar_hayoti_title_en',
        ),
        migrations.RemoveField(
            model_name='instituthaqida',
            name='rivojlanayotgan_talabalar_hayoti_title_ru',
        ),
        migrations.RemoveField(
            model_name='instituthaqida',
            name='rivojlanayotgan_talabalar_hayoti_title_uz',
        ),
        migrations.RemoveField(
            model_name='instituthaqida',
            name='sport_bilan_birga',
        ),
        migrations.RemoveField(
            model_name='instituthaqida',
            name='sport_bilan_birga_text_en',
        ),
        migrations.RemoveField(
            model_name='instituthaqida',
            name='sport_bilan_birga_text_ru',
        ),
        migrations.RemoveField(
            model_name='instituthaqida',
            name='sport_bilan_birga_text_uz',
        ),
        migrations.RemoveField(
            model_name='instituthaqida',
            name='sport_bilan_birga_title_en',
        ),
        migrations.RemoveField(
            model_name='instituthaqida',
            name='sport_bilan_birga_title_ru',
        ),
        migrations.RemoveField(
            model_name='instituthaqida',
            name='sport_bilan_birga_title_uz',
        ),
        migrations.AddField(
            model_name='instituthaqida',
            name='fayl',
            field=models.FileField(blank=True, upload_to='tadbir/fayl/'),
        ),
        migrations.AddField(
            model_name='instituthaqida',
            name='rasm',
            field=models.ImageField(blank=True, upload_to='tadbir/rasm/'),
        ),
    ]
