# Generated by Django 4.2.11 on 2024-06-27 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institut', '0004_alter_bankrekviziti_id_alter_instituthaqida_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kengash',
            name='rasm',
            field=models.ImageField(blank=True, upload_to='kengash/'),
        ),
    ]
