# Generated by Django 4.2.11 on 2024-06-29 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institut', '0005_kengash_rasm'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kengash',
            old_name='kengash_haqida',
            new_name='kengash_haqida_en',
        ),
        migrations.RenameField(
            model_name='kengash',
            old_name='kengash_vazifasi',
            new_name='kengash_haqida_ru',
        ),
        migrations.AddField(
            model_name='kengash',
            name='kengash_haqida_uz',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='kengash',
            name='kengash_vazifasi_en',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='kengash',
            name='kengash_vazifasi_ru',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='kengash',
            name='kengash_vazifasi_uz',
            field=models.TextField(blank=True),
        ),
    ]
