# Generated by Django 4.2.11 on 2024-06-29 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institut', '0006_rename_kengash_haqida_kengash_kengash_haqida_en_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kengash',
            old_name='fish',
            new_name='fish_en',
        ),
        migrations.AddField(
            model_name='kengash',
            name='fish_ru',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='kengash',
            name='fish_uz',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
