# Generated by Django 4.2.11 on 2024-10-23 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institut', '0007_rename_fish_kengash_fish_en_kengash_fish_ru_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='KorupsiyagaXabar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fish', models.CharField(blank=True, max_length=255)),
                ('telefon_nomer', models.CharField(blank=True, max_length=255)),
                ('email', models.EmailField(blank=True, max_length=255)),
                ('mavzu', models.TextField(blank=True)),
                ('xabar', models.TextField(blank=True)),
            ],
        ),
    ]
