# Generated by Django 5.0.3 on 2024-03-28 15:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Elon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rasm', models.ImageField(upload_to='elon/')),
                ('title', models.CharField(max_length=1500)),
                ('detail', models.TextField()),
                ('boshlanish_vaqti', models.CharField(max_length=500)),
                ('tugash_vaqti', models.CharField(max_length=500)),
                ('field', models.TextField()),
                ('adress', models.CharField(max_length=500)),
                ('sana', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='GalareyaTuri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tur', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Yangilik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rasm_1', models.ImageField(upload_to='yangilik/')),
                ('rasm_2', models.ImageField(upload_to='yangilik/')),
                ('rasm_3', models.ImageField(upload_to='yangilik/')),
                ('rasm_4', models.ImageField(upload_to='yangilik/')),
                ('rasm_5', models.ImageField(upload_to='yangilik/')),
                ('title_uz', models.CharField(max_length=500)),
                ('title_ru', models.CharField(max_length=500)),
                ('title_en', models.CharField(max_length=500)),
                ('subtitle_uz', models.CharField(blank=True, max_length=500)),
                ('subtitle_ru', models.CharField(blank=True, max_length=500)),
                ('subtitle_en', models.CharField(blank=True, max_length=500)),
                ('body_0_uz', models.TextField()),
                ('body_0_ru', models.TextField()),
                ('body_0_en', models.TextField()),
                ('body_1_uz', models.TextField(blank=True)),
                ('body_1_ru', models.TextField(blank=True)),
                ('body_1_en', models.TextField(blank=True)),
                ('body_2_uz', models.TextField(blank=True)),
                ('body_2_ru', models.TextField(blank=True)),
                ('body_2_en', models.TextField(blank=True)),
                ('body_3_uz', models.TextField(blank=True)),
                ('body_3_ru', models.TextField(blank=True)),
                ('body_3_en', models.TextField(blank=True)),
                ('body_4_uz', models.TextField(blank=True)),
                ('body_4_ru', models.TextField(blank=True)),
                ('body_4_en', models.TextField(blank=True)),
                ('body_5_uz', models.TextField(blank=True)),
                ('body_5_ru', models.TextField(blank=True)),
                ('body_5_en', models.TextField(blank=True)),
                ('body_6_uz', models.TextField(blank=True)),
                ('body_6_ru', models.TextField(blank=True)),
                ('body_6_en', models.TextField(blank=True)),
                ('body_7_uz', models.TextField(blank=True)),
                ('body_7_ru', models.TextField(blank=True)),
                ('body_7_en', models.TextField(blank=True)),
                ('body_8_uz', models.TextField(blank=True)),
                ('body_8_ru', models.TextField(blank=True)),
                ('body_8_en', models.TextField(blank=True)),
                ('body_9_uz', models.TextField(blank=True)),
                ('body_9_ru', models.TextField(blank=True)),
                ('body_9_en', models.TextField(blank=True)),
                ('sana', models.CharField(blank=True, max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Galareya',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rasm', models.ImageField(upload_to='galareya/')),
                ('tur_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.galareyaturi')),
            ],
        ),
    ]
