# Generated by Django 5.0.3 on 2024-03-30 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_yangilik_rasm_2_alter_yangilik_rasm_3_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fikr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rasm', models.FileField(upload_to='fikr/')),
                ('video', models.FileField(upload_to='fikr/')),
                ('text', models.CharField(blank=True, max_length=200)),
                ('talaba', models.CharField(blank=True, max_length=200)),
                ('link', models.URLField(blank=True, max_length=500)),
            ],
        ),
    ]
