# Generated by Django 5.0.3 on 2024-05-30 10:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_navbarname_navbarlink'),
        ('tuzilma', '0002_alter_bolimrahbar_biografiya_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videomaruzalar',
            name='fakultet_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tuzilma.fakultet'),
        ),
        migrations.DeleteModel(
            name='Fakultet',
        ),
    ]
