# Generated by Django 5.0.3 on 2024-04-01 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_fikr'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fikr',
            old_name='talaba',
            new_name='talaba_en',
        ),
        migrations.RenameField(
            model_name='fikr',
            old_name='text',
            new_name='talaba_ru',
        ),
        migrations.RemoveField(
            model_name='elon',
            name='adress',
        ),
        migrations.RemoveField(
            model_name='elon',
            name='detail',
        ),
        migrations.RemoveField(
            model_name='elon',
            name='field',
        ),
        migrations.RemoveField(
            model_name='elon',
            name='title',
        ),
        migrations.RemoveField(
            model_name='galareyaturi',
            name='tur',
        ),
        migrations.AddField(
            model_name='elon',
            name='adress_en',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='elon',
            name='adress_ru',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='elon',
            name='adress_uz',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='elon',
            name='detail_en',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='elon',
            name='detail_ru',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='elon',
            name='detail_uz',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='elon',
            name='field_en',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='elon',
            name='field_ru',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='elon',
            name='field_uz',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='elon',
            name='title_en',
            field=models.CharField(blank=True, max_length=1500),
        ),
        migrations.AddField(
            model_name='elon',
            name='title_ru',
            field=models.CharField(blank=True, max_length=1500),
        ),
        migrations.AddField(
            model_name='elon',
            name='title_uz',
            field=models.CharField(blank=True, max_length=1500),
        ),
        migrations.AddField(
            model_name='fikr',
            name='talaba_uz',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='fikr',
            name='text_en',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='fikr',
            name='text_ru',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='fikr',
            name='text_uz',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='galareyaturi',
            name='tur_en',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='galareyaturi',
            name='tur_ru',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='galareyaturi',
            name='tur_uz',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='elon',
            name='boshlanish_vaqti',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='elon',
            name='rasm',
            field=models.ImageField(blank=True, upload_to='elon/'),
        ),
        migrations.AlterField(
            model_name='elon',
            name='tugash_vaqti',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='fikr',
            name='rasm',
            field=models.FileField(blank=True, upload_to='fikr/'),
        ),
        migrations.AlterField(
            model_name='fikr',
            name='video',
            field=models.FileField(blank=True, upload_to='fikr/'),
        ),
        migrations.AlterField(
            model_name='galareya',
            name='rasm',
            field=models.ImageField(blank=True, upload_to='galareya/'),
        ),
        migrations.AlterField(
            model_name='yangilik',
            name='body_0_en',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='yangilik',
            name='body_0_ru',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='yangilik',
            name='body_0_uz',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='yangilik',
            name='rasm_1',
            field=models.ImageField(blank=True, upload_to='yangilik/'),
        ),
        migrations.AlterField(
            model_name='yangilik',
            name='title_en',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='yangilik',
            name='title_ru',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='yangilik',
            name='title_uz',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
