# Generated by Django 5.0.3 on 2024-04-03 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_rename_talaba_fikr_talaba_en_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='galareya',
            name='tur_id',
        ),
        migrations.AddField(
            model_name='galareya',
            name='tur_id',
            field=models.ManyToManyField(to='home.galareyaturi'),
        ),
    ]
