# Generated by Django 5.0.3 on 2024-04-29 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_remove_galareya_tur_id_galareya_tur_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hamkorlarimiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hamkor_rasm', models.FileField(blank=True, upload_to='hamkor_rasm')),
            ],
        ),
        migrations.CreateModel(
            name='Statistika',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statistika_title_uz', models.CharField(blank=True, max_length=255)),
                ('statistika_title_ru', models.CharField(blank=True, max_length=255)),
                ('statistika_title_en', models.CharField(blank=True, max_length=255)),
                ('statistika_text_uz', models.TextField(blank=True)),
                ('statistika_text_ru', models.TextField(blank=True)),
                ('statistika_text_en', models.TextField(blank=True)),
                ('talaba_title_uz', models.CharField(blank=True, max_length=255)),
                ('talaba_title_ru', models.CharField(blank=True, max_length=255)),
                ('talaba_title_en', models.CharField(blank=True, max_length=255)),
                ('talaba_nomer', models.CharField(blank=True, max_length=255)),
                ('phd_title_uz', models.CharField(blank=True, max_length=255)),
                ('phd_title_ru', models.CharField(blank=True, max_length=255)),
                ('phd_title_en', models.CharField(blank=True, max_length=255)),
                ('phd_nomer', models.CharField(blank=True, max_length=255)),
                ('oqituvchi_title_uz', models.CharField(blank=True, max_length=255)),
                ('oqituvchi_title_ru', models.CharField(blank=True, max_length=255)),
                ('oqituvchi_title_en', models.CharField(blank=True, max_length=255)),
                ('oqituvchi_nomer', models.CharField(blank=True, max_length=255)),
                ('fan_doktiri_title_uz', models.CharField(blank=True, max_length=255)),
                ('fan_doktiri_title_ru', models.CharField(blank=True, max_length=255)),
                ('fan_doktiri_title_en', models.CharField(blank=True, max_length=255)),
                ('fan_doktiri_nomer', models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
