# Generated by Django 5.0.3 on 2024-06-14 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_elektronkutubxona_id_alter_elon_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Boglanish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manzil_uz', models.CharField(blank=True, max_length=255)),
                ('manzil_ru', models.CharField(blank=True, max_length=255)),
                ('manzil_en', models.CharField(blank=True, max_length=255)),
                ('telefon', models.CharField(blank=True, max_length=255)),
                ('email_1', models.CharField(blank=True, max_length=255)),
                ('email_2', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='NavbarLink',
        ),
        migrations.DeleteModel(
            name='NavbarName',
        ),
    ]
