# Generated by Django 5.0.3 on 2024-04-29 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_hamkorlarimiz_statistika'),
    ]

    operations = [
        migrations.CreateModel(
            name='Talaba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('talaba_rasm', models.ImageField(blank=True, upload_to='talaba_rasm/')),
                ('talaba_coment_uz', models.CharField(blank=True, max_length=255)),
                ('talaba_coment_ru', models.CharField(blank=True, max_length=255)),
                ('talaba_coment_en', models.CharField(blank=True, max_length=255)),
                ('talaba_ism_uz', models.CharField(blank=True, max_length=255)),
                ('talaba_ism_ru', models.CharField(blank=True, max_length=255)),
                ('talaba_ism_en', models.CharField(blank=True, max_length=255)),
                ('talaba_inferior_uz', models.CharField(blank=True, max_length=255)),
                ('talaba_inferior_ru', models.CharField(blank=True, max_length=255)),
                ('talaba_inferior_en', models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
