# Generated by Django 5.0.3 on 2024-06-19 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_boglanish_delete_navbarlink_delete_navbarname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videomaruzalar',
            name='video',
        ),
    ]
