# Generated by Django 5.0.3 on 2024-06-20 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_remove_videomaruzalar_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vakansiya',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lavozim_uz', models.CharField(blank=True, max_length=255)),
                ('lavozim_ru', models.CharField(blank=True, max_length=255)),
                ('lavozim_en', models.CharField(blank=True, max_length=255)),
                ('bolim_uz', models.CharField(blank=True, max_length=255)),
                ('bolim_ru', models.CharField(blank=True, max_length=255)),
                ('bolim_en', models.CharField(blank=True, max_length=255)),
                ('sana', models.CharField(blank=True, max_length=255)),
                ('stavka_uz', models.CharField(blank=True, max_length=255)),
                ('stavka_ru', models.CharField(blank=True, max_length=255)),
                ('stavka_en', models.CharField(blank=True, max_length=255)),
                ('oylik_uz', models.CharField(blank=True, max_length=255)),
                ('oylik_ru', models.CharField(blank=True, max_length=255)),
                ('oylik_en', models.CharField(blank=True, max_length=255)),
                ('malakaviy_talablar_uz', models.TextField(blank=True, max_length=255)),
                ('malakaviy_talablar_ru', models.TextField(blank=True, max_length=255)),
                ('malakaviy_talablar_en', models.TextField(blank=True, max_length=255)),
            ],
        ),
    ]
