# Generated by Django 5.0.3 on 2024-04-29 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_talaba'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='galareya',
            name='tur_id',
        ),
        migrations.AddField(
            model_name='galareya',
            name='tur_id',
            field=models.ManyToManyField(to='home.galareyaturi'),
        ),
    ]
