# Generated by Django 5.0.3 on 2024-06-20 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_vakansiya'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vakansiya',
            name='malakaviy_talablar_en',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='vakansiya',
            name='malakaviy_talablar_ru',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='vakansiya',
            name='malakaviy_talablar_uz',
            field=models.TextField(blank=True),
        ),
    ]
