# Generated by Django 4.2.11 on 2024-07-01 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_vakansiya_malakaviy_talablar_en_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EfirName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_uz', models.CharField(blank=True, max_length=255)),
                ('name_ru', models.CharField(blank=True, max_length=255)),
                ('name_en', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Efir',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_uz', models.CharField(blank=True, max_length=255)),
                ('name_ru', models.CharField(blank=True, max_length=255)),
                ('name_en', models.CharField(blank=True, max_length=255)),
                ('link', models.TextField(blank=True)),
                ('efirname_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.efirname')),
            ],
        ),
    ]
