# Generated by Django 5.0.3 on 2024-06-06 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tuzilma', '0004_alter_bolim_id_alter_bolimhodim_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rektoratrahbar',
            name='rektorat_id',
        ),
    ]
