# Generated by Django 5.0.3 on 2024-06-07 04:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tuzilma', '0005_remove_rektoratrahbar_rektorat_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='rektoratrahbar',
            name='rektorat_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tuzilma.rektorat'),
            preserve_default=False,
        ),
    ]
