# Generated by Django 5.0.3 on 2024-06-19 09:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tuzilma', '0008_bolimhodim_rasm_bolimrahbar_rasm_fakultethodim_rasm_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kafedrahodim',
            name='kafedra_rahbar_id',
        ),
        migrations.AddField(
            model_name='kafedrahodim',
            name='kafedra_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tuzilma.kafedra'),
            preserve_default=False,
        ),
    ]
